### ISSUE TITLE
Please support NFS

### ISSUE THREAD

**Issue by Freyert** [cloudfoundry/bosh-softlayer-cpi-release#110]
It would be really great if you could also support creation of NFS disks as well as ISCI.

**Comment by jianqiu** [comment]
@Freyert 
Thanks for your suggestion, we will think about it since we should consider the NFS support of SolfLayer.

**Comment by mattcui** [comment]
@Freyert We are open and willing to see the code contribution from anyone who has interests in and would like to improve this project. It will be great if you could submit a PR to help us address this requirement. Thanks.

**Comment by maximilien** [comment]
@Freyert what SoftLayer APIs do you use for NSF disks...  Want to see if that's just a `cloud_config` update or need to add new API support in `softlayer-go`. 

Thanks for suggestion and any more pointers.

**Comment by Freyert** [comment]
@maximilien I'm fairly unfamiliar with the Softlayer API, but I'd like to get more involved. I love the stuff going on with Terraform. I'll have to swing by softlayer-go.

**Comment by mattcui** [comment]
No plan to support NFS.
