### ISSUE TITLE
Why does a network IP influence which path actions.CreateVM#Run goes down?

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi-release#117]
Commit https://github.com/cloudfoundry/bosh-softlayer-cpi/commit/f1ee110c291d52ca39a13327824e52dba14f3588 introduced a conditional flow through the `create_vm` action but there are _no tests_ to describe why it was done or to keep it from getting regressed.

Can you please explain why an IP address is used as the condition that selects OS reload vs. creation?
What condition results in the presence or absence of an IP?
Why aren't there any tests to cover this code?

Thanks.

**Comment by mattcui** [comment]
If an IP is passed from director to CPI createvm function, it means there is trying to do something for an existing VM, for Bluemix/Softlayer, we need to do os reload instead of recreation. We will add some test when we get time. Thanks.

**Comment by maximilien** [comment]
Some context: `os_relead` was a unique SoftLayer feature that will actually now be part of all CPIs. See bosh tracker story: [#114037725](https://www.pivotaltracker.com/story/show/114037725).

That does not justify any lack of tests converage. So @mattcui please add a chore in tracker for this listing some tests you plan to add and close this issue with a pointer to that chore. Thx.

**Comment by sykesm** [comment]
My concern isn't about whether to reload or not to reload, my concern is why the IP address is used as the mechanism to determine whether or not to go down that path.

I'm experimenting with manual networks on softlayer (with good success) and using the IP as the sentinel is forcing the CPi to go down the reload path even when the VM does not exist. Since there's no test coverage, I simply commented out the block to make progress but it's not the right thing to do.

**Comment by mattcui** [comment]
@sykesm It looks like a bug to me when handling static IP (manual network), CPI should check if there is an existing VM with the given IP which is passed in from director. If there is, do os reload, otherwise create a new VM. If you agree with the solution, I will open a bug to CPI.

From all info passed from director into CPI, only IP address can be used to help identify if the target VM exists or not, so we have to use it to distinguish whether to do os reload or create a new VM.

Thanks.

**Comment by sykesm** [comment]
@mattcui I agree it's a bug but it's more than just using the IP from the network configuration.

Unless something changes at SoftLayer, they will always allocate a primary backend IP address for the private network. You can use this IP with a dynamic network configuration to find the VM but you can't use it from a manual network to find the associated VM. The front end, public networks behave similarly but, as you know, there's no requirement to connect the VM to a public network.

The path I'm on right now to support an explicit IP assignment will require both a dynamic and a manual network configuration for the VM; both networks will need to be associated with the same VLAN. The dynamic configuration will get an address from the "primary" subnet configuration on the VLAN and the manual configuration will use an address from a portable (or routed to vlan) subnet.

When networking is configured on the VM, both addresses will be associated with associated with the network interface for the VLAN. The configuration that is marked as having the default gateway will be assigned the base adapter name (eg. eth0) and be associated with the default route while the others will be assigned an aliased adapter name(eg. eth0:0).

A configuration like this should enable people to bring up VMs in a deployment with addresses that are known a-priori. This is necessary to deploy a "standard" `cf-release` configuration without running through multiple deployments.

/cc @smoser-ibm @fraenkel

**Comment by jianqiu** [comment]
@sykesm 
Thanks for your detailed explanation.
If I understand you correctly, the following scenario you mentioned had been implemented in our legacy CPI which was written in ruby.

_"When networking is configured on the VM, both addresses will be associated with associated with the network interface for the VLAN. The configuration that is marked as having the default gateway will be assigned the base adapter name (eg. eth0) and be associated with the default route while the others will be assigned an aliased adapter name(eg. eth0:0)."_

For eCPI, we ever considered this requirement, though not the implementation, because we did not have the full understanding of SL portable IP at that time, as you know, SL did not provider API to assign second IP address to aliased adapter (eth0:0) directly, we should modify /etc/network/interfaces manually or by script, this may be somewhat difficult to implement it in eCPI. Do you have any ideas?
Thanks!

Now, we are considering to using network type to switch different behavior between dynamic and manual network, the following is unfinished codes, I will submit PR when it is ready.

```
func (c *softLayerVirtualGuestCreator) Create(agentID string, stemcell bslcstem.Stemcell, cloudProps VMCloudProperties, networks Networks, env Environment) (VM, error) {
	for _, network := range networks {
		switch network.Type {
		case "dynamic":
			if len(network.IP) == 0 {
				return c.createBySoftlayer(agentID, stemcell, cloudProps, networks, env)
			} else {
				return c.createByOSReload(agentID, stemcell, cloudProps, networks, env)
			}
		case "manual":
			return softLayerVirtualGuest{}, bosherr.Error("Support manual netowrk soon...")
		case "vip":
			return softLayerVirtualGuest{}, bosherr.Error("SoftLayer Not Support VIP netowrk")
		default:
			return softLayerVirtualGuest{}, bosherr.Errorf("Softlayer Not Support This Kind Of Network: %s", network.Type)
		}
	}
}
```

**Comment by sykesm** [comment]
The code I'm working on now generates /etc/network/interfaces from a template and transfers it to the target VM before the agent user data is created and uploaded. Since you're already hard-coding 'preconfigured` to `true` on the network definitions, the bosh-agent should leave well enough alone.

After the transfer, I'm hoping that bouncing the interfaces will work. Since the primary IP will still be valid, the connection may die but reconnects will work. I hope to know if this works shortly. If it does, then I think it's a matter of finding when and where that behavior needs to occur.

**Comment by sykesm** [comment]
I have my prototype of manual networks deployed. I'm able to use bosh init to bring up a director on a plan and associate it with a portable IP. The code is incomplete but it's at the point where I think someone with more expertise in the CPI should take a look at it...  I'll point you to a branch shortly.

That said, we still can't use the CPI to deploy easily deploy cloud foundry to soft layer.  The templates, as they exist in cf-release, do not assume multiple networks. Updating the templates to allow a manual and dynamic exercises a bug in spiff (which is unlikely to get fixed since the infrastructure team doesn't want to update spiff any longer <sigh/>) where only a single network shows up and the properties from both networks are merged.

Manually fixing the template allows the deployment to continue but then we have the issue were the metron agent template doesn't render because the ip in a dynamic network is nil. Issues [loggregator/#129][1] and [bosh/#1206][2] capture this problem.

I'd like to be able to have a single manual type network that uses portable IPs but that breaks assumptions in the current CPI around IP's and the reload path...

So, that brings me back to this issue.  Are there ways to have reload work without assuming that an IP is the primary backend IP for the guest?

[1]: https://github.com/cloudfoundry/loggregator/issues/129 
[2]: https://github.com/cloudfoundry/bosh/issues/1206

**Comment by maximilien** [comment]
Ok, @sykesm, thanks for your efforts to improve the CPI/SL IP usage. 

Let me discuss with team this week and create some stories to investigate and see how we can support this. Do note that the team is working on current features to support upgrade of Bluemix dedicated/public (ongoing) and baremetal, so I need to figure out what makes sense in term of priority. I'll post stories/updates here when available.

Best.

**Comment by cppforlife** [comment]
btw bosh#1206 was patched in latest 256.x version. released on friday.

**Comment by maximilien** [comment]
Tracker story [#121895629](https://www.pivotaltracker.com/story/show/121895629)

**Comment by sykesm** [comment]
spike is #130
