### ISSUE TITLE
Long hostname prefix breaks persistent disk acquisition

### ISSUE THREAD

**Issue by jszroberto** [cloudfoundry/bosh-softlayer-cpi-release#129]
Long hostname prefixes on nodes with persistent disk configured like the following XX-XXXXXX-XXXXX-XXXXX-database- displayed the following error: 

Failed creating bound missing vms > database/0: Creating VM with agent ID '87881d1c-5cfd-453c-ad35-ba0177971fe6': Updating VM's agent env: Updating Agent Env timeout: Uploading temporary file to destination '/var/vcap/bosh/user_data.json': ssh: handshake failed: EOF (00:12:47)
   Failed creating bound missing vms (00:12:47)

The problem was caused by the long host name which is too long to generate ssh

For example this XX-XXXXXX-XXXXX-XXXXX-db- prefix work and we could get the new VM with persistent disk without any issue. 

Can you implement something to solve this problem in the next cpi version? 

At least, the CPI should inform you that the hostname are too long when parsing the configuration.

**Comment by maximilien** [comment]
Thanks for reporting this issue @jszroberto. This is reasonable and fair request.

Let me look into if this is due to a limitation of SL in naming VMs and if there is a way around it. A t a minimum we should offer you a better log message as you suggested. Best.

**Comment by mattcui** [comment]
As I mentioned in another thread, it should be a problem with SL, but we could mitigate this problem from the side of eCPI before SL fixes the issue. I opened SL ticket [31097913](https://control.softlayer.com/support/tickets/31097913) to wonder how long of hostname at maximal is allowed to create a VM without that ssh problem, we will improve eCPI to pre-check the length of hostname passed in and make the deployment failed if it beyonds the maximal length.

**Comment by mattcui** [comment]
Opened the story [SSH connection failed due to long hostname](https://www.pivotaltracker.com/story/show/127718453), will implement in eCPI v2

/cc @jszroberto  @maximilien

**Comment by maximilien** [comment]
Thanks @mattcui OK cool. Leaving this open.

@jszroberto is this satisfactory for you. Do you have a work around now? Trying to gage the importance of this fix for you. Let us know. Thx.

**Comment by jszroberto** [comment]
@maximilien @mattcui this is highly affecting our deployments. and the issue happens only when hostname is equal to 64.

**Comment by jszroberto** [comment]
Can you tackle this issue?

**Comment by maximilien** [comment]
@jszroberto this is limitation in SoftLayer and not sure there is anything more we can do. Perhaps you can have some scripts that simplify your hostnames before sending them. For instance, use the first n number of characters and postfix it with some hash of the rest of the letters...

**Comment by zhanggbj** [comment]
Please note PR #205 is reverted. Please find the details in the comments. Thanks.

**Comment by mattcui** [comment]
The issue is solved by [PR 226](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/pull/226)
