### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by zhanggbj** [cloudfoundry/bosh-softlayer-cpi-release#183]
Hi @dr.max,

Please help to rename this repository when it is convenient as currently it seems have some PRs in review, so I opened an issue to track this thing. Thank you.

**Comment by maximilien** [comment]
I am ready to do this. I will wait and do it once we talk after CNY. Please remind me @zhanggbj

**Comment by maximilien** [comment]
Cool. Doing now.

/cc @cppforlife  @gu-bin we need to also change links in bosh.io

**Comment by gu-bin** [comment]
@maximilien I didn't find any link references in bosh.io

**Comment by maximilien** [comment]
Cool, thanks @gu-bin. Just wanted to verify. Best.
