### ISSUE TITLE
Improve doc for `sudo bosh-init`

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh-softlayer-cpi-release#190]
#187 was closed after merging https://github.com/cloudfoundry/docs-bosh/pull/270, but my comments in that PR weren't addressed.

At least https://github.com/cloudfoundry/docs-bosh/pull/270#pullrequestreview-15455253 should be addressed (i.e. change the terminal instructions from `bosh-init` to `sudo bosh-init`) to make it immediately obvious how to run `bosh-init`.

Sorry for being picky about this, but I think we should take every opportunity to avoid problems when using this CPI.

**Comment by gu-bin** [comment]
https://github.com/cloudfoundry/docs-bosh/pull/271 will fix it

**Comment by maximilien** [comment]
@gu-bin's PR was merged so closing this.
