### ISSUE TITLE
CF Manifest Generation

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi-release#207]
Are there any templates or stubs information that can be used for manifest generation when deploying CF? Creating a manifest by hand is really difficult and hard to keep up to date. Also, it would be nice if we could get detailed section information about what we need in the manifest. For example, the [aws stubs](http://docs.cloudfoundry.org/deploying/aws/cf-stub.html#editing) provides a detailed list of all the required properties to override.

**Comment by maximilien** [comment]
That's a good suggestion. Let me see what's possible

**Comment by maximilien** [comment]
There is also another related issue #128

**Comment by gu-bin** [comment]
IBM Bluemix has the CF YML templates for different CF versions. You can get them from github.ibm.com.
