### ISSUE TITLE
Targeting the bosh director

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi-release#210]
After standing up the bosh director via bosh-init, there is no information on how to target the actual director. When looking at [bosh docs](http://bosh.io/docs/init-softlayer.html#deploy) it says to just target the IP, but that IP needs to be found when looking at the newly provisioned bosh vm in the softlayer ui. Also, it is documented to login with `admin` as the username and password, but those really need to be found in the deployment manifest.

**Comment by maximilien** [comment]
Cool, that's a good suggestion. Let me assign this to @gu-bin who can add the necessary docs when she is back from Chinese New Year vacation. 

Thanks for opening the issue.

**Comment by mattcui** [comment]
@DanLavine You could get the director IP from /etc/hosts, we will try to document it better. 

/cc @gu-bin

**Comment by gu-bin** [comment]
PR https://github.com/cloudfoundry/docs-bosh/pull/271 added instruction on how to get the director ip. The login user/password is not set in the deployment manifest but created from ``bosh create user`` command https://bosh.io/docs/director-users.html. Default is admin/admin.

**Comment by DanLavine** [comment]
@mattcui Why would I look at /etc/hosts after I deploy Bosh to get the IP address? That seems scary that /etc/hosts will be modified. What if there is already an entry in there for bosh. Will it be overwritten and remove what I could have manually added myself? Are there guarantees that everything there is preserved?

@gu-bin The `admin` `admin` username and password only work if there are no users created at startup. However, the director properties in the example manifest says to fill in a username and password

**Comment by gu-bin** [comment]
added in commit https://github.com/cloudfoundry/docs-bosh/pull/271/commits/61ef9c5fb40c076f4fd37265db45f7544c05fdef

**Comment by mattcui** [comment]
@DanLavine Yes, there has to update /etc/hosts to support current Bluemix environments on Softlayer (use dynamic IP as static IP for directors), there had many discussions about it, but we can't figure out a better way to handle this situation. Currently, /etc/hosts is overwritten, Yes I agree it's bad to not preserve the existing data. We could consider to append the new DNS entry at the bottom of /etc/hosts. 

@jianqiu do you think if it's better to append rather than overwrite? Any potential problem? Thanks.

**Comment by maximilien** [comment]
@mattcui and @jianqiu let's try appending. Please update progress here. Thx

**Comment by mattcui** [comment]
@maximilien Opened [bug #140753119](https://www.pivotaltracker.com/story/show/140753119) to track this issue.

**Comment by maximilien** [comment]
Thanks @mattcui, let's prioritize this for @DanLavine and let him know here when someone picks up that story. Thx

**Comment by mattcui** [comment]
The PR has been merged, so close this issue now.

**Comment by maximilien** [comment]
Thanks @mattcui
