### ISSUE TITLE
Properties are different between bosh and CF

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi-release#211]
The `VMNamePrefix` property different for bosh-init vs bosh when deploying CF. in Bosh-init it really means the hostname for the VM,  so cannot end with certain characters. Could we get some clearer information about these fields or rename one of them?

**Comment by maximilien** [comment]
I believe Bluemix needed this due to some limitation in SL. 

@mattcui can you please confirm the background on this. Thx

**Comment by mattcui** [comment]
@DanLavine there has to pre-define the fully qualified hostname in bosh-init yaml, CPI will set the DNS mapping in /etc/hosts, so there can't append a timestamp like CF jobs. @gu-bin will give an explanation/attention in http://bosh.io/docs/softlayer-cpi.html

**Comment by gu-bin** [comment]
PR https://github.com/cloudfoundry/docs-bosh/pull/271

**Comment by DanLavine** [comment]
@mattcui My issue is not that a timestamp is append in the CF jobs, but that the same property has different meanings depending on what the manifest is trying to deploy:

1. The property is `VMNamePrefix` in bosh-init, but it really defines what the VM name is. It feels like this should be named `VMName` since that is what it is really doing and when looking [here](http://bosh.io/docs/init-softlayer.html), there is nothing to say what the properties are really doing.

2. `VMNamePrefix` + an appended timestamp is used when creating a VM for CF, or some other bosh deployed system.

As an aside, why do we need this property and not just name the VM with the name of the actual job?

**Comment by maximilien** [comment]
Guys (@mattcui and @gu-bin) let's discuss this tonight in scrum. @DanLavine makes a good point. Consistency should be paramount, unless Bluemix or other large users have already adopted the current scheme.

**Comment by mattcui** [comment]
@DanLavine Yes, I agree to use another name like `hostname`, @jianqiu and @maximilien, if you all agree, I will open one story and implement it, but maybe we still need to keep the backward compatibility for a while before we delete `VMNamePrefix` completely. 

The properties used for creating a VM are defined under `resource_pool`,  currently, we set the job name and index as tags to the VM.

**Comment by mattcui** [comment]
Sorry, I accidentally closed this issue, feel free to continue to post comments here or open a new issue.

**Comment by maximilien** [comment]
Reopening. We need to discuss this tomorrow night

**Comment by mattcui** [comment]
Opened tracker to address this issue -> https://www.pivotaltracker.com/story/show/139523259, @DanLavine please let us know if you don't think  the new name `Hostname` is proper. Thanks.

**Comment by DanLavine** [comment]
@mattcui Looks fine to me.

**Comment by maximilien** [comment]
Cool, closing this. @DanLavine feel free to add yourself to the Tracker story to monitor if you so desire. Best.
