### ISSUE TITLE
Error 100: Could not auto-detect IP version for ''.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/bosh-softlayer-cpi-release#218]
The following error occurs when i recreate/restart vm via bosh.

$ bosh recreate haproxy 0
...
Error 100: Could not auto-detect IP version for ''.

Softlater D/C: Seoul
CPI version : 3.0.5
Bosh version : 260.6
Stemcell version : 3312.18

**Comment by mattcui** [comment]
@YunSangJun Please post your yml or send to cuixuex@cn.ibm.com and wangjq@cn.ibm.com, don't forget to hide all sensitive data there. Thanks.

**Comment by YunSangJun** [comment]
@mattcui I sent my yml file to the email.

Thanks.

**Comment by mattcui** [comment]
@jianqiu Could you please help take look at his manifest? I guess there is something improper in Network section. Thanks.

**Comment by gu-bin** [comment]
@jianqiu I think the manifest is OK. Would you please take a look? Maybe it's a bug in our code?

**Comment by maximilien** [comment]
@YunSangJun, can you please share some logs? As a reminder you can easily get logs from any tasks using the `$bosh` CLI (old or new) with:
```
$ bosh task [TASK_ID] [--event] [--cpi] [--debug] [--result] [--raw]
```
Please ensure you remove any sensitive data when sharing here. Use the `--cpi` to share the CPI logs which should be especially interesting for us to see. Thx.

**Comment by maximilien** [comment]
What is the status of this issue?

**Comment by maximilien** [comment]
Hi, @YunSangJun, are you still seeing this with latest CPI release (find in [bosh.io](https://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release?all=1))? If yes, please share logs. Otherwise, I will close this as resolved.

**Comment by mattcui** [comment]
Closing for no response 
/cc @maximilien
