### ISSUE TITLE
Support shared iSCSI disk for multiple VMs.

### ISSUE THREAD

**Issue by libingw** [cloudfoundry/bosh-softlayer-cpi-release#219]
We used to manually order machines and an iSCSI disk from softlayer portal. Then we authorized the  same disk to multiple servers. We then installed and ran some iSCSI and mpath commands in the servers to configure the disk sharing. For example, if 2 VMs share the same disk, the lsblk commands from the two VMs shares the same disk ID:
From server1:
sda                                                  8:0    0    20G  0 disk  
└─3600a098038303753723f49474361794f (dm-1)         252:1    0    20G  0 mpath 
  └─3600a098038303753723f49474361794f-part1 (dm-2) 252:2    0    20G  0 part  
sdb                                                  8:16   0    20G  0 disk  
└─3600a098038303753723f49474361794f (dm-1)         252:1    0    20G  0 mpath 
  └─3600a098038303753723f49474361794f-part1 (dm-2) 252:2    0    20G  0 part  

From Server2:
sde                                                                          8:64   0    20G  0 disk  
└─3600a098038303753723f49474361794f (dm-3)                                 252:3    0    20G  0 mpath 
  └─3600a098038303753723f49474361794f-part1 (dm-6)                         252:6    0    20G  0 part  
sdf                                                                          8:80   0    20G  0 disk  
└─3600a098038303753723f49474361794f (dm-3)                                 252:3    0    20G  0 mpath 
  └─3600a098038303753723f49474361794f-part1 (dm-6)                         252:6    0    20G  0 part  

Based on this lsblk result, we will then use "dm-2" and "dm-6" to configure our parallel file system.

Here are 2 questions I have so far:
1. Is it possible to configure BOSH in the yml file so that a iSCSI disk can be shared?
2. BOSH maps the iSCSI disk to /var/vcap/store, is there options not to do this? So that after the VM is created, the lsblk command will show the same thing as I mentioned above?

**Comment by mattcui** [comment]
@maximilien I don't think BOSH/CPI support such scenario, what's your opinion? I don't think it's a common or general requirement.

/cc @jianqiu

**Comment by maximilien** [comment]
Yeah, not quite. Any such setup is ideally done by the bosh-agent. We can certainly discuss it.

Generally, I don't believe sharing disks should be done at the BOSH layer. Perhaps using a service is best. Please take a look at the [CF-persistence](https://www.cloudfoundry.org/creating-cloud-foundry-applications-with-persistence/) [project](https://www.pivotaltracker.com/n/projects/1518687) which has goals to essentially allow container-level sharing of storage using a special kind of CF-service.

/cc @cppforlife who I am sure has an opinion on this topic.

**Comment by maximilien** [comment]
@libingw I suggest you raise this with BOSH. When/if such scenario is supported we will look into adding. Closing for now.
