### ISSUE TITLE
minimal-softlayer example manifest hardcodes JWT signing key and other sensitive values

### ISSUE THREAD

**Issue by cantino** [cloudfoundry/bosh-softlayer-cpi-release#223]
https://github.com/cloudfoundry/bosh-softlayer-cpi-release/blob/master/docs/mimimal-softlayer.yml#L839

Anyone using this manifest, even for experimentation, will have a CF installation that will accept bearer tokens from any other similar installation, or from anyone who spoofs their JWT tokens with this shared private key. Those values in the example manifest should be replaced with placeholders such as `REPLACE_WITH_UAA_JWT_SIGNING_PRIVATE_KEY`, `REPLACE_WITH_UAA_JWT_VERIFICATION_PUBLIC_KEY`, etc.

Additionally, there are a bunch of other sensitive hardcoded default values in this manifest.

**Comment by mattcui** [comment]
@zhanggbj Could you please help address problems. Thanks.

**Comment by zhanggbj** [comment]
Hi @cantino, 

Thank you for noticing this! I just submitted a PR #224  to fix it. Thanks.

/cc @mattcui

**Comment by cantino** [comment]
Great, thanks @zhanggbj!

**Comment by maximilien** [comment]
Fixed.
