### ISSUE TITLE
Deployment fails with stemcell ubuntu-trusty version 3363.9

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh-softlayer-cpi-release#228]
Our latest deployment in Softlayer tried using the newest ubuntu-trusty stemcell version 3363.9 and failed with the error 
```
CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '5285bda5-41d6-44d6-bb5c-db06ae7aff4d': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method
```

Do we have to change something in the Cloud Config with this new stemcell version?

Help is appreciated. Thanks,
Peter

_Full deployment log here:_

```
Deploying
---------

Director task 6860
  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > nginx/1c8867c98ccd77c9f8d5509ec8e6993681125bf3
  Started compiling packages > bits-common/31323f35fea0d06665c3ffdd9019605655cdcb99
  Started compiling packages > ruby-2.3/af291eea8a7bf463720143128a1f25a7b6e9f56c
  Started compiling packages > yajl/0508cba03499f6efc467759285a1ef8b34838450
  Started compiling packages > python/484075d81d41ce3985fa299004a82d96c9a24aa7
   Failed compiling packages > ruby-2.3/af291eea8a7bf463720143128a1f25a7b6e9f56c: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '5285bda5-41d6-44d6-bb5c-db06ae7aff4d': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method (00:11:36)
   Failed compiling packages > nginx/1c8867c98ccd77c9f8d5509ec8e6993681125bf3: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '1cdc9ebb-a866-448d-bde6-d45b035d3296': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method (00:11:43)
   Failed compiling packages > yajl/0508cba03499f6efc467759285a1ef8b34838450: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '041d1de8-87fb-48b4-8a3e-7e15eec40c2f': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method (00:11:47)
   Failed compiling packages > python/484075d81d41ce3985fa299004a82d96c9a24aa7: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '71e9a0a5-4e7a-4608-b980-cea1f005a8ca': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method (00:11:48)
   Failed compiling packages > bits-common/31323f35fea0d06665c3ffdd9019605655cdcb99: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '1d6be408-c678-48f4-b480-1193073d1b25': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method (00:13:37)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '5285bda5-41d6-44d6-bb5c-db06ae7aff4d': Updating VM's agent env: Updating Agent Env timeout. : Upload to "/var/vcap/bosh/user_data.json" failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain' in 'create_vm' CPI method

Task 6860 error

For a more detailed error report, run: bosh task 6860 --debug
command 'bosh -n --color -t https://10.155.171.25 -d /tmp/bosh_manifest20170315-6-oswicm deploy --no-redact' failed!

```

/cc @suhlig @smoser-ibm

**Comment by petergtz** [comment]
Is #131 related to this issue?

**Comment by maximilien** [comment]
@gu-bin have we tested stemcell version 3363.9 with our pipeline? Did not see this.

/cc @mattcui @zhanggbj

**Comment by mattcui** [comment]
Yes, It's a known problem with the stemcell 3363.9, but since the sha1 can't be overridden on bosh.io once it's already uploaded, we can't upload the good stemcell there. In addition, we are still working on the new pipeline for building the stemcell for catching up the community. In the meantime, you could try with the stemcell below, please let us know if you meet any problem. Thanks.

https://s3.amazonaws.com/bosh-softlayer-stemcells-candidate-container/light-bosh-stemcell-3363.12-softlayer-xen-ubuntu-trusty-go_agent.tgz

**Comment by petergtz** [comment]
> In the meantime, you could try with the stemcell below, please let us know if you meet any problem. Thanks.
>
> https://s3.amazonaws.com/bosh-softlayer-stemcells-candidate-container/light-bosh-stemcell-3363.12-softlayer-xen-ubuntu-trusty-go_agent.tgz

@mattcui That's not really a viable option, because we're using concourse's stemcell resource. For the time being we're using the old stemcell version.

Can you add information to the broken stemcell version on bosh.io to make it obvious that there is an issue? It took me several hours to find out that it's the stemcell and not something else.

**Comment by mattcui** [comment]
@petergtz  I totally agree, and sorry for wasting your time. @jianqiu tomorrow it's your last day working in Pivotal, possible to talk to the pair chair (or some senior guy there) to see if it's possible to fix this issue, or if it's possible to add some warning messages there at least? Thanks.

/cc @maximilien

**Comment by mattcui** [comment]
@petergtz We have a new stemcell [3363.12.1](https://s3.amazonaws.com/bosh-softlayer-cpi-stemcells/light-bosh-stemcell-3363.12.1-softlayer-xen-ubuntu-trusty-go_agent.tgz) published on bosh.io. Please note that there requires to to add `keep_root_password` property under resouce_pool due to a change in `bosh-agent`, you could reference the sample [docs/sl-bosh.yml](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/blob/master/docs/sl-bosh.yml#L15-L17)

**Comment by valeriap** [comment]
@mattcui How do I specify `keep_root_password: true` in v2 manifests? Is the property under `instance_groups`? Thanks.

**Comment by mattcui** [comment]
@valeriap Yes, I think so.

**Comment by petergtz** [comment]
@valeriap Maybe I'm missing something, but aren't you confusing the deployment manifest with a *bosh director* manifest? [docs/sl-bosh.yml](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/blob/master/docs/sl-bosh.yml#L15-L17) is a sample manifest to deploy a *bosh director*. Hence, there's no Cloud Config to update.

@mattcui Thanks for the update. We'll this one as soon as possible.

**Comment by valeriap** [comment]
@petergtz Since the property is used by the bosh agent I supposed the change to be needed on each deployment, not specifically on the bosh director deployment. Am I wrong?

**Comment by petergtz** [comment]
@valeriap No idea. @mattcui?

**Comment by mattcui** [comment]
@petergtz @valeriap if you want to use it in manifest v2, I think you have to define `keep_root_password` in cloud_config.

**Comment by petergtz** [comment]
@mattcui Would it make sense to update the cloud_config.yml template to make it clear then? 

Also, you wrote you "think" it has to be defined there. Does that mean it is unclear at this point?

**Comment by mattcui** [comment]
@petergtz I am working on this these days, just submitted [PR 55](https://github.com/cloudfoundry/bosh-deployment/pull/55), you or @valeriap could reference `cpi.yml` and `cloud-config.yml` in  [softlayer](https://github.com/mattcui/bosh-deployment/tree/softlayer/softlayer). The property `keep_root_password` has to be defined under `instance_groups`, reference -> [concourse_sample_v2_schema.yml](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/blob/master/docs/concourse_sample_v2_schema.yml#L65-L67)
