### ISSUE TITLE
CPI should power off free VMs in the VPS pool and tagged them as free 

### ISSUE THREAD

**Issue by jszroberto** [cloudfoundry/bosh-softlayer-cpi-release#252]
Hi @mattcui @maximilien, 

Could you evaluate the possibility to power off machines when they are released as marked as `free` state? 

It will be also interesting to add VMs tags to identify if they are in the pool and specially if they are `free`. In that way, you could identify all the idle VMs you have in your SL account. 

Maybe `vps-free`, `vps-provisioning`, `vps-running` could be the tags.

**Comment by maximilien** [comment]
Thanks for suggestion @jszroberto. I'll chat with the team tomight in our scrum call

/cc rest of team: @jianqiu, @zhanggbj, and @gu-bin

**Comment by mattcui** [comment]
@maximilien @jszroberto already talked to me before opening this issue, yes, we can have a talk about it in scrum.

**Comment by mattcui** [comment]
@jszroberto As you know, there maintains status (like `free`, `provisioning`, `using` and `unknown`) in VPS db, I recalled that when we tried to implement the VPS solution, the original idea is to leverage tags, but there is a concurrency issue, like a case that BOSH requests 15 VMs from pool at the same time. So it's why we changed to use DB to maintain the status. I think we could address your 1st requirement to power off the VM when it's returned into pool. But it's not easy and it might be kind of duplicated since there already tracked status in VPS DB. What do you think? Thanks.

**Comment by jszroberto** [comment]
@mattcui  Apart from powering off the VM (priority 1), it might be enough for us to have a tag saying that a VM is registered or was created by the pool in the VPS pool on the Softlayer side, like `bosh-pool`. In that way, our team and specially other teams, will see those VMs as being handled by our team without having to understand if there is a pool or not or how to check the pool. 

On the other hand,  we could also check the consistency of the entries in our VPS pool comparing the information given by the pool and by the SL api.

**Comment by EdwardStudy** [comment]
@jszroberto As consider for your team, The `vps-manage` tag maybe work on your situation. 

The tag design is that the VM created by the VPS pool will be added `vps-manage` tag, and anything about tags do not changes when the VM is recollected by the VPS poll. You can query the tag to check if VMs are created by the VPS pool. 

So how do you think about using this method to specify to the creation of VMs. Thank you.

**Comment by jszroberto** [comment]
@EdwardStudy that would work

**Comment by mattcui** [comment]
@jszroberto we will deliver CPI NG, do you still have this requirement? Thanks.

**Comment by mattcui** [comment]
Closing this one, please re-open if you still have the requirement.

**Comment by jszroberto** [comment]
@mattcui We still have the same requirement, but I guess it can wait until you publish the CPI NG.

**Comment by mattcui** [comment]
@jszroberto do you know if some ones/teams are really still using VPS? We still have capacity problem in SL DCs? Thanks.

**Comment by jszroberto** [comment]
@mattcui I've just double-checked VPS is enabled only for short periods of time. 

In the past we were adding more and more VMs to the pool, but not any longer. 

Consequently, this requirement is not that important now as it was 1 year ago.

**Comment by mattcui** [comment]
Thanks for the double check.
