### ISSUE TITLE
Deployment fails with bosh-softlayer-xen-ubuntu-trusty-go_agent 3421.11

### ISSUE THREAD

**Issue by valeriap** [cloudfoundry/bosh-softlayer-cpi-release#253]
I'm trying to deploy with the latest stemcell but the deployment fails during compilation with error:

```
07:03:59 | Compiling packages: cflinuxfs2/ae0dd4491d9439d8648045677e9b3e3516815815 (00:17:53)
            L Error: Timed out pinging to 9366a3d4-0a7d-4646-bf3a-42fc9ebffd27 after 600 seconds
```
Note that the vm is created within the 600 seconds.
With an older stemcell it works fine (I've tried 3363.20.1) .

Bosh director is `261.3.0`
Thanks,
Valeria.

**Comment by mattcui** [comment]
There should be some compatibility issue in agent of softlayer community stemcell. We will try to fix it soon.

https://s3.amazonaws.com/bosh-softlayer-stemcells-bluemix/light-bosh-stemcell-3421.9.3-bluemix-xen-ubuntu-trusty-go_agent.tgz

@jianqiu more and more people met this problem, could you please help build a new stemcell with compatible bosh-agent? Thanks.

**Comment by EdwardStudy** [comment]
@valeriap Hi, we upgrade stemcell to v3431.13.3, it fixes the issue. And we prefer to use BOSH director v262.3+.

I hope this helps you.

**Comment by valeriap** [comment]
Thanks.
