### ISSUE TITLE
CPI error 'Can not find VirtualGuestBlockDeviceTemplateGroup with id ...'

### ISSUE THREAD

**Issue by 7CHANHO** [cloudfoundry/bosh-softlayer-cpi-release#259]
## ISSUE
When I tried to upload the stemcell, a CPI error occurred.
```
# bosh upload stemcell light-bosh-stemcell-3431.13.3-softlayer-xen-ubuntu-trusty-go_agent.tgz 
Acting as user 'admin' on 'bosh'
...
  Started update stemcell > Uploading stemcell bosh-softlayer-xen-ubuntu-trusty-go_agent/3431.13.3 to the cloud. Failed: CPI error 'Bosh::Clouds::CloudError' with message 'Finding stemcell with ID '1710621': Can not find VirtualGuestBlockDeviceTemplateGroup with id `1710621`' in 'create_stemcell' CPI method (00:00:30)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Finding stemcell with ID '1710621': Can not find VirtualGuestBlockDeviceTemplateGroup with id `1710621`' in 'create_stemcell' CPI method
```

## CONTEXT
I used the following version of the release.
- bosh: 262.3
- bosh-softlayer-cpi: 23
- bosh-softlayer-xen-ubuntu-trusty-go_agent: 3431.13.3

**Comment by EdwardStudy** [comment]
@7CHANHO Hi~ 
The error is meaning that system image id `1710621` can not found in Softlayer image templates.(And I checked that it does not exist in portal) You could just try the latest version like `3445.2.1`.

Hope this helps!

**Comment by 7CHANHO** [comment]
@EdwardStudy Hello.
I have found my problem. Since bosh is not connected to the public network, it is determined that a timeout has occurred during the API call.
```
bosh/0:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         PRIVATE_GW  0.0.0.0         UG    0      0        0 eth0
10.0.0.0        PRIVATE_GW  255.0.0.0       UG    0      0        0 eth0
PRIVATE_IP  0.0.0.0         255.255.255.192 U     0      0        0 eth0
PUBLIC_IP      PRIVATE_GW  255.255.0.0     UG    0      0        0 eth0
PUBLIC_IP       0.0.0.0         255.255.255.240 U     0      0        0 eth1
bosh/0:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
```
When I added the public network gateway, then the connection became possible.
Also, uploading the stemcell is now possible.

How do I configure the manifest to distribute bosh to connect to the public network?

**Comment by EdwardStudy** [comment]
Yes, I see that you used [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment.git). We fixed the gateway error in our own [repo](https://github.com/bluebosh/bosh-deployment/tree/softlayer).  But the PR merge may be laterly. 

You can use the [repo](https://github.com/bluebosh/bosh-deployment/tree/softlayer) temporarily if you need. 

Thank you.

**Comment by 7CHANHO** [comment]
@EdwardStudy Thank You :)
