### ISSUE TITLE
CPI error 'Cannot find the billing item for this virtual server'

### ISSUE THREAD

**Issue by 7CHANHO** [cloudfoundry/bosh-softlayer-cpi-release#260]
## CONTEXT
I used the following version of the release.
- bosh: 263
- bosh-softlayer-cpi: 23
- bosh-softlayer-xen-ubuntu-trusty-go_agent: 3445.2.1

## ISSUE
When I tried to recreate the job, a CPI error occurred.
```
# bosh -e mybosh -d ntp recreate ntpd/2
Using environment '<BOSH-IP>' as client 'admin'

Using deployment 'ntp'

Continue? [yN]: y

Task 64

08:53:15 | Preparing deployment: Preparing deployment (00:00:00)
08:53:15 | Preparing package compilation: Finding packages to compile (00:00:00)
08:53:15 | Updating instance ntpd: ntpd/d054e429-9012-4863-b7d1-b360525b8067 (2) (canary) (00:00:14)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID 'a0eedcfe-42c6-4ae0-8f50-3af3306e748d': Failed to reload OS: Failed to reload OS on the specified VirtualGuest from SoftLayer client: Cannot find the billing item for this virtual server (sl-20170904-084458-512.softlayer.com).' in 'create_vm' CPI method

08:53:29 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID 'a0eedcfe-42c6-4ae0-8f50-3af3306e748d': Failed to reload OS: Failed to reload OS on the specified VirtualGuest from SoftLayer client: Cannot find the billing item for this virtual server (sl-20170904-084458-512.softlayer.com).' in 'create_vm' CPI method

Started  Mon Sep  4 08:53:15 UTC 2017
Finished Mon Sep  4 08:53:29 UTC 2017
Duration 00:00:14

Task 64 error

Changing state:
  Expected task '64' to succeed but was state is 'error'

Exit code 1
```

## QUESTION
Why does this error occur? Do I need special permissions to recreate?

**Comment by 7CHANHO** [comment]
When I tried to deploy Cloud Foundry using `cf-deployment`, the same error has occurred.
```
# bosh -d cf deploy cf-deployment.yml -o operations/softlayer.yml --vars-store deployment-vars.yml -v system_domain=DOMAIN
06:47:37 | Updating instance consul: consul/4ee72950-ab7e-4163-a690-f80c63ccb197 (0) (canary) (00:01:06)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating Virtual_Guest with agent ID '01e32b1d-ae28-4adb-be92-ff2823f58ee2': Failed to reload OS: Failed to reload OS on the specified VirtualGuest from SoftLayer client: Cannot find the billing item for this virtual server (sl-20170905-022554-998.softlayer.com).' in 'create_vm' CPI method
```

**Comment by EdwardStudy** [comment]
The error message was said that `virtual server (sl-20170905-022554-998.softlayer.com)` was not exist (meaning was deleted). As a default, Bosh would delete VM from the cloud when instance update. And director has `enable_virtual_delete_vms` [property](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=director.enable_virtual_delete_vms) to specify this behaviour.

So I suggest that you set `enable_virtual_delete_vms` as `true` in `/instance_groups/name=bosh/properties/director/enable_virtual_delete_vms`.

Hope it can works!

**Comment by mattcui** [comment]
@7CHANHO You could reference https://github.com/bluebosh/bosh-deployment/blob/softlayer/softlayer/cpi.yml#L76, here is property spec -> https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=263#p=director.enable_virtual_delete_vms

**Comment by 7CHANHO** [comment]
Thank you @EdwardStudy @mattcui 
I have solved this problem.
