### ISSUE TITLE
How to use softlayer private endpoint?.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/bosh-softlayer-cpi-release#262]
Hello.

How to use softlayer private endpoint?.

The following is guide for softlayer REST API.
Use "api.service.softlayer.com/rest/v3/" to access the REST API over SoftLayer's private network.
https://sldn.softlayer.com/article/rest

**Comment by mattcui** [comment]
@YunSangJun sorry for late reply, you can specify an api endpoint in the following feature option

http://bosh.io/jobs/softlayer_cpi?source=github.com/cloudfoundry/bosh-softlayer-cpi-release&version=23#p=softlayer.featureOptions.apiEndpoint
