### ISSUE TITLE
Option to select VM type as Private Node

### ISSUE THREAD

**Issue by 7CHANHO** [cloudfoundry/bosh-softlayer-cpi-release#264]
Hello.
I am currently deploying Cloud Foundry on SoftLayer using bosh-softlayer-cpi.
But I want to deploy VM as a private node, not a public node.
Is there an option to select VM type as private node in bosh-softlayer-cpi?
I look forward to your reply.

**Comment by EdwardStudy** [comment]
@7CHANHO Hi, You could set property `dedicatedAccountHostOnlyFlag: true` in cloud_property and deploy new VMs. You can find this property in [local properties](https://sldn.softlayer.com/reference/datatypes/SoftLayer_virtual_guest).

I hope it helps you.

**Comment by 7CHANHO** [comment]
Thank you for your reply, @EdwardStudy 
That's what I was looking for.
Let me ask you one more question.
If this property is set to true, will the VSI host be assigned automatically?
Is this the same procedure as selecting 'auto assign' in the soft layer console?

**Comment by mattcui** [comment]
@7CHANHO I think so, as you may know, SL started to support to allow the user to order a host and provision VMs on the host, our CPI hasn't support this new feature, will look at it soon.
