### ISSUE TITLE
Bosh panics at external bosh command softlayer cpi

### ISSUE THREAD

**Issue by anthony-loupos** [cloudfoundry/bosh-softlayer-cpi-release#273]
I'm following the instructions at https://bosh.io/docs/init-softlayer/#vlan but when trying to deploy the Director it panics.  I think this is the relevant snippet: 

`{"accountId":<redacted>,"createDate":"2018-01-23T02:21:18-05:00","id":<redacted>,"name":"light-bosh-stemcell-3468.20-softlayer-xen-ubuntu-trusty-go_agent","note":"Public_light_stemcell_3468.20","parentId":null,"publicFlag":1,"statusId":1,"summary":"Public_light_stemcell_3468.20","transactionId":null,"userRecordId":247176,"accountReferences":[],"globalIdentifier":"58ad4767-3383-461b-9e35-89355ce6b6cb"}
panic: interface conversion: interface is string, not float64

goroutine 1 [running]:
panic(0x8d2780, 0xc4200700c0)
	/root/.bosh/installations/00875b6f-c979-475a-68ce-4485f433ee04/packages/golang_1.7.1/src/runtime/panic.go:500 +0x1a1
bosh-softlayer-cpi/softlayer/common.configureNetworkVlan(0xc420508a50, 0xc4203e87f0, 0x956694, 0x2)
	/root/.bosh/installations/00875b6f-c979-475a-68ce-4485f433ee04/packages/bosh_softlayer_cpi/src/bosh-softlayer-cpi/softlayer/common/vm_utils.go:244 +0x151
bosh-softlayer-cpi/softlayer/common.configureNetwork(0xc420508a20, 0xc4205262c0, 0x964501)
`

This is for an important demo in FSS, would greatly appreciate any help to resolve.

**Comment by edwardstudy** [comment]
@anthony-loupos You should set sl_vlan_public/sl_vlan_private as the number.
