### ISSUE TITLE
Need retry if there fails to check active transaction from SL

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#298]
```L Error: CPI error 'Bosh::clouds::CloudError' with message 'Attaching ephemeral disk to VM with id 'xxxxxxxx': Waiting until instance has none active transaction before os_reload: WSDL: SOAP-ERROR: Parsing Schema: can't import schema from 'https://applb101-loopback.softlayer.local/v3.1/sldn/soap/SoftLayer_Virtual_Guest?xsd' (HTTP 500)' in 'create_vm' CPI method```

In addition, need to correct the wrong msg `before os_reload`, this issue didn't occur in os reload case.

**Comment by rkoster** [comment]
@gu-bin Any update on this? Or can this issue be closed?

**Comment by rkoster** [comment]
@donacarr Do you have any context on this issue?
