### ISSUE TITLE
Need to renew `softlayer ci ssl certificate` cert and move to the corresponding domain

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#300]
@dpb587-pivotal Dmitriy ever gave us the cert for cpi and stemcell ci/cd pipeline site for IBM Cloud. through LastPass (`softlayer ci ssl certificate`), it's already expired, could you please help renew it? Actually we didn't use it before, do you know what domain is addressed by this cert, we need to apply for the domain name through aws route53? Thanks.

/cc @jfmyers9 @mfine30

**Comment by dpb587-pivotal** [comment]
I do not think we are managing CI environments nor certificates for SoftLayer. I do not know what environment you are referring to - can you be more specific?

If this concerns sensitive environments or details, please start an email thread with us instead of a public GitHub issue.

**Comment by mattcui** [comment]
After some discussions with Danny, we decided to try with `Let's Encrypt`, there is a bosh release for use or reference -> https://github.com/dpb587/caddy-bosh-release

**Comment by mattcui** [comment]
Requested a new cert for `bosh-sl-ci.bluemix.net` from `Let's Encrypt", closing this issue.
