### ISSUE TITLE
`Potential file inclusion via variable` from GoSec scan

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#304]
Reference -> https://stackoverflow.com/questions/52320708/how-to-handle-gosec-linter-warning-potential-file-inclusion-via-variable/52321435

**Comment by edwardstudy** [comment]
It was still warning after accept https://stackoverflow.com/a/52321933/3804444. 

The only thing to do about the warning is to suppress or ignore it.
