### ISSUE TITLE
`Use of weak cryptographic primitive` from GoSec scan

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#307]

**Comment by edwardstudy** [comment]
CPI uses MD5 to digest stemcell parts to check each part integrity. It does not work to import the bad image if attackers forge MD5 digest.

**Comment by edwardstudy** [comment]
About object file collision, swift(>=1.9.0) will identify md5 collisions on objects and sens a 403: https://github.com/openstack/swift/commit/caa01cd81e7dae6c41c1ffb8a69aed6ff70777cf
